import { Geist, Geist_Mono } from "next/font/google";
import "./css/globals.css";
import "./css/icon/style.css";
import "./css/shortcodes.css";
import "./css/responsive.css";
import "./css/animation.css";
import "./css/nouislider.min.css";
import "./css/map.min.css";
import "./css/magnific-popup.min.css";
import "./css/animate.min.css";
import "./css/swiper-bundle.min.css";
import "./css/font/font.css";
import "./css/bootstrap.css";
import Header from "./components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Centrum Menu",
  description: "Generated by Centrum Menu",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="body">
           <div id="wrapper">
            <div id="page">
            <Header/>
            {children}
            </div>
          </div>
      </body>
    </html>
  );
}
