import { Geist, Geist_Mono } from "next/font/google";
import "@/app/css/globals.css";
import "@/app/css/icon/style.css";
import "@/app/css/shortcodes.css";
import "@/app/css/responsive.css";
import "@/app/css/animation.css";
import "@/app/css/nouislider.min.css";
import "@/app/css/map.min.css";
import "@/app/css/magnific-popup.min.css";
import "@/app/css/animate.min.css";
import "@/app/css/swiper-bundle.min.css";
import "@/app/css/font/font.css";
import "@/app/css/bootstrap.css";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import CustomCursor from "@/app/components/CustomCursor";
import ProgressBar from "@/app/components/ProgressBar";
import { Toaster } from "sonner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Centrum Menu",
  description: "Generated by Centrum Menu",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="body">
           <div id="wrapper">
            <div id="page">
              <Header/>
              {children}
              <Footer/>
            </div>
          </div>
          <CustomCursor />
          <ProgressBar />
          <Toaster
            position="top-right"
            toastOptions={{
              style: {
                background: "#198754",
                color: "#fff",
                border: "1px solid #198754",
              },
            }}
          />
      </body>
    </html>
  );
}
